version: '3.1'
networks:
  elk:
services:
  elasticsearch:
    image: elasticsearch:6.4.1
    ports:
      - 9200:9200
    networks:
      - elk

  kibana:
    image: kibana:6.4.1
    ports:
      - 5601:5601
    networks:
      - elk